nome = str(input('Digite o seu nome completo: ')).strip().upper()
n = nome.split()
print('Muito Prazer em te conheçer {} !'.format(nome))
print('O seu primeiro nome é {}.'.format(n[0]))
print('O seu último nome é {}.'.format(n[-1]))